SELECT DISTINCT 
    t1.USER_ID, 
    t1.PRODUCT_ID
FROM 
    ONLINE_SALE t1
JOIN 
    ONLINE_SALE t2 
ON 
    t1.USER_ID = t2.USER_ID 
    AND t1.PRODUCT_ID = t2.PRODUCT_ID 
    AND t1.SALES_DATE > t2.SALES_DATE
ORDER BY 
    t1.USER_ID ASC, 
    t1.PRODUCT_ID DESC;