WITH ReviewCounts AS (
    SELECT MEMBER_ID, COUNT(*) AS ReviewCount
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MaxReviewers AS (
    SELECT MEMBER_ID
    FROM ReviewCounts
    WHERE ReviewCount = (SELECT MAX(ReviewCount) FROM ReviewCounts)
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (SELECT MEMBER_ID FROM MaxReviewers)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;
